name: Code Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule: # Build every day at 5PM UTC
    - cron: '0 17 * * *'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1
  GH_TOKEN: ${{ github.token }}

jobs:
  Format-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run cargo fmt check
        run: cargo fmt --all -- --check

  all-feature-combinations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cargo-all-features
        run: cargo install cargo-all-features

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wayland-client

      - name: cargo check-all-features
        run: cargo check-all-features

  web-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: add wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Install cargo binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install trunk
        run: cargo binstall trunk

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wayland-client

      - name: wasm32 trunk build
        run: make -C piggui trunk-build

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y wayland-client

      - name: run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --tests --no-deps --all-features --all-targets
